#include "markdownmay/export/docx_writer.hpp"
#include <algorithm>
#include <fstream>
#include <iterator>
#include <map>
#include <functional>
#include <utility>
#include <string>
namespace markdownmay::exporting { namespace {
using Bytes=std::vector<std::uint8_t>;struct Entry{std::string name;Bytes data;std::uint32_t crc{},offset{};};
void U16(Bytes&o,std::uint16_t v){o.push_back(v&255);o.push_back(v>>8);}void U32(Bytes&o,std::uint32_t v){for(int i=0;i<4;++i)o.push_back((v>>(i*8))&255);}void Add(Bytes&o,std::string_view s){o.insert(o.end(),s.begin(),s.end());}
std::uint32_t Crc(const Bytes&b){std::uint32_t c=0xffffffffU;for(auto x:b){c^=x;for(int i=0;i<8;++i)c=(c>>1)^((0U-(c&1U))&0xedb88320U);}return ~c;}
bool Zip(const std::filesystem::path&p,std::vector<Entry> e){if(e.size()>65535)return false;Bytes o;for(auto&x:e){if(x.data.size()>0xffffffffULL||x.name.size()>65535)return false;x.crc=Crc(x.data);x.offset=static_cast<std::uint32_t>(o.size());U32(o,0x04034b50);U16(o,20);U16(o,0x800);U16(o,0);U16(o,0);U16(o,0);U32(o,x.crc);U32(o,static_cast<std::uint32_t>(x.data.size()));U32(o,static_cast<std::uint32_t>(x.data.size()));U16(o,static_cast<std::uint16_t>(x.name.size()));U16(o,0);Add(o,x.name);o.insert(o.end(),x.data.begin(),x.data.end());}auto central=static_cast<std::uint32_t>(o.size());for(const auto&x:e){U32(o,0x02014b50);U16(o,20);U16(o,20);U16(o,0x800);U16(o,0);U16(o,0);U16(o,0);U32(o,x.crc);U32(o,static_cast<std::uint32_t>(x.data.size()));U32(o,static_cast<std::uint32_t>(x.data.size()));U16(o,static_cast<std::uint16_t>(x.name.size()));for(int i=0;i<4;++i)U16(o,0);U32(o,0);U32(o,x.offset);Add(o,x.name);}auto size=static_cast<std::uint32_t>(o.size())-central;U32(o,0x06054b50);U16(o,0);U16(o,0);U16(o,static_cast<std::uint16_t>(e.size()));U16(o,static_cast<std::uint16_t>(e.size()));U32(o,size);U32(o,central);U16(o,0);std::ofstream f(p,std::ios::binary|std::ios::trunc);f.write(reinterpret_cast<const char*>(o.data()),static_cast<std::streamsize>(o.size()));return f.good();}
std::string X(std::string_view s){std::string o;for(char c:s){if(c=='&')o+="&amp;";else if(c=='<')o+="&lt;";else if(c=='>')o+="&gt;";else if(c=='\"')o+="&quot;";else o+=c;}return o;}
std::string Text(const ExportNode&n){if(n.kind==document::NodeKind::formula_inline)return "[公式："+n.text+"]";if(n.kind==document::NodeKind::formula_block)return "[块公式："+n.text+"]";std::string o=n.text;for(const auto&c:n.children)o+=Text(c);return o;}
std::string Run(std::string_view s,std::string_view props={}){return "<w:r><w:rPr>"+std::string(props)+"</w:rPr><w:t xml:space=\"preserve\">"+X(s)+"</w:t></w:r>";}
void Inline(const ExportNode&n,std::string&o,std::map<document::NodeId,std::string>&links){if(n.kind==document::NodeKind::image){auto found=links.find(n.source_id);if(found==links.end()){o+=Run("[图片不可用："+Text(n)+"]");return;}o+="<w:r><w:drawing><wp:inline xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\"><wp:extent cx=\"4572000\" cy=\"2571750\"/><wp:docPr id=\"1\" name=\"Image\" descr=\""+X(Text(n))+"\"/><a:graphic xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\"><a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><pic:pic xmlns:pic=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><pic:nvPicPr><pic:cNvPr id=\"0\" name=\"Image\"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed=\""+found->second+"\"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"4572000\" cy=\"2571750\"/></a:xfrm><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>";return;}std::string prop;if(n.kind==document::NodeKind::strong)prop="<w:b/>";else if(n.kind==document::NodeKind::emphasis)prop="<w:i/>";else if(n.kind==document::NodeKind::strike)prop="<w:strike/>";else if(n.kind==document::NodeKind::inline_code)prop="<w:rFonts w:ascii=\"Consolas\" w:hAnsi=\"Consolas\"/><w:shd w:fill=\"F2F4F7\"/>";if(n.kind==document::NodeKind::text||n.kind==document::NodeKind::inline_code||n.kind==document::NodeKind::formula_inline||n.kind==document::NodeKind::formula_block){o+=Run(Text(n),prop);return;}if(n.kind==document::NodeKind::link){o+="<w:hyperlink r:id=\""+links[n.source_id]+"\" w:history=\"1\">";for(const auto&c:n.children)Inline(c,o,links);o+="</w:hyperlink>";return;}for(const auto&c:n.children)Inline(c,o,links);}
std::string Para(const ExportNode&n,std::string_view style,std::map<document::NodeId,std::string>&links,std::string_view extra={}){std::string o="<w:p><w:pPr>";if(!style.empty())o+="<w:pStyle w:val=\""+std::string(style)+"\"/>";o+=extra;o+="</w:pPr>";if(n.children.empty())o+=Run(Text(n));else for(const auto&c:n.children)Inline(c,o,links);return o+"</w:p>";}
void Block(const ExportNode&n,std::string&o,std::map<document::NodeId,std::string>&links,int depth=0){switch(n.kind){case document::NodeKind::heading:{int l=1;if(auto*a=std::get_if<document::HeadingAttributes>(&n.attributes))l=a->level;o+=Para(n,"Heading"+std::to_string(l),links,"<w:ind w:left=\""+std::to_string((l-1)*240)+"\"/>");break;}case document::NodeKind::paragraph:o+=Para(n,"",links);break;case document::NodeKind::quote:o+="<w:p><w:pPr><w:pStyle w:val=\"Quote\"/></w:pPr>"+Run(Text(n))+"</w:p>";break;case document::NodeKind::code_block:o+="<w:p><w:pPr><w:pStyle w:val=\"Code\"/></w:pPr>"+Run((std::get_if<document::CodeAttributes>(&n.attributes)&&std::get_if<document::CodeAttributes>(&n.attributes)->language=="mermaid"?"[Mermaid 源码]\n":"")+n.text)+"</w:p>";break;case document::NodeKind::list:{auto*a=std::get_if<document::ListAttributes>(&n.attributes);for(const auto&i:n.children){std::string value;if(auto*li=std::get_if<document::ListItemAttributes>(&i.attributes);li&&li->task)value=li->checked?"[x] ":"[ ] ";for(const auto&c:i.children)if(c.kind!=document::NodeKind::list)value+=Text(c);o+="<w:p><w:pPr><w:numPr><w:ilvl w:val=\""+std::to_string(depth)+"\"/><w:numId w:val=\""+std::string(a&&a->ordered?"2":"1")+"\"/></w:numPr></w:pPr>"+Run(value)+"</w:p>";for(const auto&c:i.children)if(c.kind==document::NodeKind::list)Block(c,o,links,depth+1);}break;}case document::NodeKind::table:{o+="<w:tbl><w:tblPr><w:tblW w:w=\"9360\" w:type=\"dxa\"/><w:tblInd w:w=\"120\" w:type=\"dxa\"/><w:tblBorders><w:top w:val=\"single\" w:sz=\"4\"/><w:left w:val=\"single\" w:sz=\"4\"/><w:bottom w:val=\"single\" w:sz=\"4\"/><w:right w:val=\"single\" w:sz=\"4\"/><w:insideH w:val=\"single\" w:sz=\"4\"/><w:insideV w:val=\"single\" w:sz=\"4\"/></w:tblBorders></w:tblPr>";std::size_t cols=1;for(const auto&s:n.children)if(!s.children.empty())cols=(std::max)(cols,s.children[0].children.size());o+="<w:tblGrid>";for(std::size_t i=0;i<cols;++i)o+="<w:gridCol w:w=\""+std::to_string(9360/cols)+"\"/>";o+="</w:tblGrid>";bool head=true;for(const auto&s:n.children)for(const auto&r:s.children){o+="<w:tr>"+(head?std::string("<w:trPr><w:tblHeader/></w:trPr>"):std::string{});for(const auto&c:r.children)o+="<w:tc><w:tcPr><w:tcW w:w=\""+std::to_string(9360/cols)+"\" w:type=\"dxa\"/>"+(head?"<w:shd w:fill=\"F2F4F7\"/>":"")+"</w:tcPr><w:p>"+Run(Text(c),head?"<w:b/>":"")+"</w:p></w:tc>";o+="</w:tr>";head=false;}o+="</w:tbl>";break;}default:{auto t=Text(n);if(!t.empty())o+="<w:p>"+Run(t)+"</w:p>";break;}}}
Bytes B(std::string s){return Bytes(s.begin(),s.end());}
}
ErrorCode WriteDocx(const ExportDocument&d,const std::filesystem::path&p,const CancellationToken&c,const ExportProgressSink&progress){if(c.is_cancelled())return ErrorCode::export_cancelled;std::map<document::NodeId,std::string> links;std::vector<Entry> media;std::string rels="<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering\" Target=\"numbering.xml\"/>";int rid=3;std::function<void(const ExportNode&)>scan=[&](const ExportNode&n){if(n.kind==document::NodeKind::link)if(auto*a=std::get_if<document::LinkAttributes>(&n.attributes)){auto id="rId"+std::to_string(rid++);links[n.source_id]=id;rels+="<Relationship Id=\""+id+"\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink\" Target=\""+X(a->target)+"\" TargetMode=\"External\"/>";}if(n.kind==document::NodeKind::image){auto resource=std::find_if(d.resources.begin(),d.resources.end(),[&](const ExportResource&r){return r.source_id==n.source_id;});if(resource!=d.resources.end()&&resource->state==ExportResourceState::embedded&&!resource->bytes.empty()){auto id="rId"+std::to_string(rid++);auto name="image"+std::to_string(media.size()+1)+".bin";links[n.source_id]=id;rels+="<Relationship Id=\""+id+"\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image\" Target=\"media/"+name+"\"/>";media.push_back({"word/media/"+name,resource->bytes});}}for(const auto&x:n.children)scan(x);};for(const auto&b:d.blocks)scan(b);rels+="</Relationships>";std::string body;for(std::size_t i=0;i<d.blocks.size();++i){if(c.is_cancelled())return ErrorCode::export_cancelled;Block(d.blocks[i],body,links);if(progress)progress({ExportStage::writing,static_cast<std::uint32_t>(10+(i+1)*60/(std::max)(std::size_t{1},d.blocks.size())),100});}
std::string doc="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><w:body>"+body+"<w:sectPr><w:pgSz w:w=\"11906\" w:h=\"16838\"/><w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\"/></w:sectPr></w:body></w:document>";
std::string styles="<?xml version=\"1.0\" encoding=\"UTF-8\"?><w:styles xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii=\"Microsoft YaHei\" w:hAnsi=\"Microsoft YaHei\" w:eastAsia=\"Microsoft YaHei\"/><w:sz w:val=\"22\"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type=\"paragraph\" w:default=\"1\" w:styleId=\"Normal\"><w:name w:val=\"Normal\"/><w:pPr><w:spacing w:after=\"120\" w:line=\"264\" w:lineRule=\"auto\"/></w:pPr></w:style>";for(int i=1;i<=6;++i)styles+="<w:style w:type=\"paragraph\" w:styleId=\"Heading"+std::to_string(i)+"\"><w:name w:val=\"heading "+std::to_string(i)+"\"/><w:basedOn w:val=\"Normal\"/><w:pPr><w:keepNext/><w:outlineLvl w:val=\""+std::to_string(i-1)+"\"/><w:spacing w:before=\"240\" w:after=\"120\"/></w:pPr><w:rPr><w:b/><w:color w:val=\"2E74B5\"/><w:sz w:val=\""+std::to_string((std::max)(22,34-i*2))+"\"/></w:rPr></w:style>";styles+="<w:style w:type=\"paragraph\" w:styleId=\"Quote\"><w:name w:val=\"Quote\"/><w:basedOn w:val=\"Normal\"/><w:pPr><w:ind w:left=\"360\"/></w:pPr><w:rPr><w:i/><w:color w:val=\"555555\"/></w:rPr></w:style><w:style w:type=\"paragraph\" w:styleId=\"Code\"><w:name w:val=\"Code\"/><w:basedOn w:val=\"Normal\"/><w:rPr><w:rFonts w:ascii=\"Consolas\" w:hAnsi=\"Consolas\"/><w:sz w:val=\"20\"/></w:rPr></w:style></w:styles>";
std::string numbering="<?xml version=\"1.0\" encoding=\"UTF-8\"?><w:numbering xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">";for(int id=1;id<=2;++id){numbering+="<w:abstractNum w:abstractNumId=\""+std::to_string(id)+"\">";for(int l=0;l<9;++l)numbering+="<w:lvl w:ilvl=\""+std::to_string(l)+"\"><w:start w:val=\"1\"/><w:numFmt w:val=\""+std::string(id==1?"bullet":"decimal")+"\"/><w:lvlText w:val=\""+std::string(id==1?"•":"%1.")+"\"/><w:pPr><w:tabs><w:tab w:val=\"num\" w:pos=\""+std::to_string(720+l*360)+"\"/></w:tabs><w:ind w:left=\""+std::to_string(720+l*360)+"\" w:hanging=\"360\"/></w:pPr></w:lvl>";numbering+="</w:abstractNum><w:num w:numId=\""+std::to_string(id)+"\"><w:abstractNumId w:val=\""+std::to_string(id)+"\"/></w:num>";}numbering+="</w:numbering>";
std::vector<Entry>e{{"[Content_Types].xml",B("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Default Extension=\"bin\" ContentType=\"image/png\"/><Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/><Override PartName=\"/word/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml\"/><Override PartName=\"/word/numbering.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml\"/></Types>")},{"_rels/.rels",B("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/></Relationships>")},{"word/document.xml",B(doc)},{"word/styles.xml",B(styles)},{"word/numbering.xml",B(numbering)},{"word/_rels/document.xml.rels",B(rels)},{"docProps/core.xml",B("<?xml version=\"1.0\" encoding=\"UTF-8\"?><cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\"/>")},{"docProps/app.xml",B("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\"><Application>Markdown May</Application></Properties>")}};e.insert(e.end(),std::make_move_iterator(media.begin()),std::make_move_iterator(media.end()));return Zip(p,std::move(e))?ErrorCode::ok:ErrorCode::export_target_failed;}
ErrorCode ValidateDocx(const std::filesystem::path&p){
 std::ifstream f(p,std::ios::binary);Bytes b{std::istreambuf_iterator<char>(f),{}};
 auto u16=[&](std::size_t n){return static_cast<std::uint16_t>(b[n]|(static_cast<std::uint16_t>(b[n+1])<<8));};
 auto u32=[&](std::size_t n){return static_cast<std::uint32_t>(b[n])|(static_cast<std::uint32_t>(b[n+1])<<8)|(static_cast<std::uint32_t>(b[n+2])<<16)|(static_cast<std::uint32_t>(b[n+3])<<24);};
 if(b.size()<22)return ErrorCode::export_validation_failed;std::size_t eocd=std::string::npos;
 const auto begin=b.size()>(22+65535)?b.size()-(22+65535):0;
 for(std::size_t n=b.size()-22;;--n){if(u32(n)==0x06054b50U){eocd=n;break;}if(n==begin)break;}
 if(eocd==std::string::npos||eocd+22+u16(eocd+20)!=b.size())return ErrorCode::export_validation_failed;
 const auto count=u16(eocd+10);const auto central_size=u32(eocd+12);std::size_t pos=u32(eocd+16);
 if(pos+central_size!=eocd)return ErrorCode::export_validation_failed;std::map<std::string,bool> names;
 for(std::uint16_t i=0;i<count;++i){if(pos+46>b.size()||u32(pos)!=0x02014b50U)return ErrorCode::export_validation_failed;const auto name_len=u16(pos+28);const auto extra_len=u16(pos+30);const auto comment_len=u16(pos+32);const auto local=u32(pos+42);if(pos+46+name_len+extra_len+comment_len>b.size()||local+30>b.size()||u32(local)!=0x04034b50U)return ErrorCode::export_validation_failed;names.emplace(std::string(reinterpret_cast<const char*>(b.data()+pos+46),name_len),true);pos+=46+name_len+extra_len+comment_len;}
 if(pos!=eocd)return ErrorCode::export_validation_failed;
 for(const auto*required:{"[Content_Types].xml","_rels/.rels","word/document.xml","word/styles.xml","word/numbering.xml","word/_rels/document.xml.rels"})if(!names.contains(required))return ErrorCode::export_validation_failed;
 return ErrorCode::ok;
}
ErrorCode ExportDocx(const ExportDocument&d,const std::filesystem::path&p,const CancellationToken&c,const ExportProgressSink&s){return RunExportTask(d,p,WriteDocx,ValidateDocx,c,s);}
}
