#pragma once

#define IDI_MARKDOWNMAY 101
#define IDI_MARKDOWN_DOCUMENT 102
#define IDI_TEXT_DOCUMENT 103
#define IDD_ABOUT 202
#define IDC_ABOUT_LINKS 203
#define IDC_ABOUT_PORTRAIT 204
#define IDR_ABOUT_PORTRAIT_PNG 205
