#pragma once

#define IDI_MARKDOWNMAY 101
#define IDI_MARKDOWN_DOCUMENT 102
#define IDI_TEXT_DOCUMENT 103
#define IDD_ABOUT 202
#define IDC_ABOUT_LINKS 203
#define IDC_ABOUT_PORTRAIT 204
#define IDR_ABOUT_PORTRAIT_PNG 205
#define IDD_WECHAT 206
#define IDR_ABOUT_WECHAT_JPG 207
#define IDR_ABOUT_GITHUB_PNG 208
#define IDR_ABOUT_GITEE_PNG 209
#define IDR_ABOUT_EMAIL_PNG 210
#define IDR_ABOUT_WECHAT_PNG 211

#define IDC_ABOUT_APP_ICON 220
#define IDC_ABOUT_NAME 221
#define IDC_ABOUT_ENGLISH_NAME 222
#define IDC_ABOUT_VERSION 223
#define IDC_ABOUT_TAGLINE 224
#define IDC_ABOUT_DESCRIPTION 225
#define IDC_ABOUT_CONTACT_TITLE 226
#define IDC_ABOUT_EMAIL_ICON 227
#define IDC_ABOUT_EMAIL_LINK 228
#define IDC_ABOUT_WECHAT_ICON 229
#define IDC_ABOUT_WECHAT_LINK 230
#define IDC_ABOUT_GITHUB_ICON 231
#define IDC_ABOUT_GITHUB_LINK 232
#define IDC_ABOUT_GITEE_ICON 233
#define IDC_ABOUT_GITEE_LINK 234
#define IDC_ABOUT_ISSUES_LINK 235
#define IDC_ABOUT_SEPARATOR 236
#define IDC_ABOUT_COPYRIGHT 237
#define IDC_ABOUT_CLOSE 238
#define IDC_WECHAT_QR 240
#define IDC_WECHAT_HINT 241
